name: Build ESP32-S3 (single merged factory image)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO + esptool
        run: |
          pip install --upgrade platformio esptool
          # v5: use the subcommand, not --version
          esptool version

      - name: Build (PlatformIO)
        run: pio run -e esp32-s3-zero

      - name: Merge images -> one firmware file at 0x0
        run: |
          # Standard ESP32-S3 offsets; align with Arduino/ESP-IDF upload layout
          # bootloader@0x0, partitions@0x8000, boot_app0@0xE000, app@0x10000
          python -m esptool --chip esp32s3 merge_bin \
            -o .pio/build/esp32-s3-zero/firmware-merged.bin \
            --flash_mode qio --flash_freq 80m --flash_size 4MB \
            0x0     .pio/build/esp32-s3-zero/bootloader.bin \
            0x8000  .pio/build/esp32-s3-zero/partitions.bin \
            0xE000  .pio/build/esp32-s3-zero/boot_app0.bin \
            0x10000 .pio/build/esp32-s3-zero/firmware.bin

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-s3-zero-images
          path: |
            .pio/build/esp32-s3-zero/bootloader.bin
            .pio/build/esp32-s3-zero/partitions.bin
            .pio/build/esp32-s3-zero/boot_app0.bin
            .pio/build/esp32-s3-zero/firmware.bin
            .pio/build/esp32-s3-zero/firmware-merged.bin
