name: Build ESP32-S3 Firmware

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build firmware
        run: pio run -e esp32-s3


      - name: Upload firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-s3-images
          path: |
            .pio/build/esp32-s3/bootloader.bin
            .pio/build/esp32-s3/partitions.bin
            .pio/build/esp32-s3/boot_app0.bin
            .pio/build/esp32-s3/firmware.bin
      

