name: Build ESP32-S3 (single merged factory image)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PIO_ENV: esp32-s3-zero   # <-- must match your [env:...] name in platformio.ini

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install PlatformIO + esptool
        run: |
          pip install --upgrade platformio esptool
          esptool version   # v5 syntax; don't use --version

      - name: Build (PlatformIO)
        run: pio run -e $PIO_ENV

      - name: Merge images -> one firmware file at 0x0
        shell: bash
        run: |
          set -euo pipefail
          BUILD_DIR=".pio/build/${PIO_ENV}"

          BOOTLOADER="${BUILD_DIR}/bootloader.bin"
          PARTITIONS="${BUILD_DIR}/partitions.bin"
          APPBIN="${BUILD_DIR}/firmware.bin"

          # boot_app0.bin may not be produced in BUILD_DIR by PIO; find a fallback in packages
          BOOTAPP0="${BUILD_DIR}/boot_app0.bin"
          if [[ ! -f "$BOOTAPP0" ]]; then
            BOOTAPP0="$(find ~/.platformio/packages -type f -name 'boot_app0.bin' | head -n 1 || true)"
          fi

          echo "Resolved files:"
          ls -l "$BOOTLOADER" "$PARTITIONS" "$APPBIN"
          if [[ -n "${BOOTAPP0:-}" && -f "$BOOTAPP0" ]]; then
            echo "Using boot_app0.bin: $BOOTAPP0"
          else
            echo "ERROR: boot_app0.bin not found"; exit 1
          fi

          # Create single merged image with standard ESP32-S3 offsets
          python -m esptool --chip esp32s3 merge-bin \
            --flash-mode qio --flash-freq 80m --flash-size 4MB \
            -o "${BUILD_DIR}/firmware-merged.bin" \
            0x0     "$BOOTLOADER" \
            0x8000  "$PARTITIONS" \
            0xE000  "$BOOTAPP0" \
            0x10000 "$APPBIN"

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: esp32-s3-zero-images
          path: |
            .pio/build/${{ env.PIO_ENV }}/bootloader.bin
            .pio/build/${{ env.PIO_ENV }}/partitions.bin
            .pio/build/${{ env.PIO_ENV }}/boot_app0.bin
            .pio/build/${{ env.PIO_ENV }}/firmware.bin
            .pio/build/${{ env.PIO_ENV }}/firmware-merged.bin
