name: Build ESP32 Firmware

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write  # Required to create releases and upload files

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build Firmware
        run: platformio run --environment esp32dev
        env:
          PLATFORMIO_BUILD_FLAGS: -D VERSION=\"${{ env.VERSION }}\"

      - name: Rename Firmware for OTA
        run: cp .pio/build/esp32dev/firmware.bin ESP32-LED-OTA.bin

      - name: Upload Firmware as Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Firmware ${{ github.ref }}
          body: Auto-built firmware from tag.
          files: |
            .pio/build/esp32dev/firmware.bin
            ESP32-LED-OTA.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
