name: Build ESP32 Firmware

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Extract Version from Tag
        id: extract_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "Extracted version: $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build Firmware
        run: platformio run --environment esp32dev
        env:
          PLATFORMIO_BUILD_FLAGS: -D VERSION=\"${{ env.VERSION }}\"

      - name: Upload Firmware Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ESP32-Firmware
          path: .pio/build/esp32dev/firmware.bin

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: Firmware ${{ github.ref }}
          body: Auto-built firmware from tag.
          files: .pio/build/esp32dev/firmware.bin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
