name: Build and Release ESP32-S3 Firmware

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PlatformIO
        run: pip install -U platformio

      - name: Build firmware
        run: pio run -e esp32-s3

      - name: Install GitHub CLI
        run: sudo apt update && sudo apt install gh -y

      - name: Create Release and Upload Firmware
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} \
            .pio/build/esp32-s3/firmware.bin \
            --title "Release ${{ github.ref_name }}" \
            --notes "Automated build of ESP32-S3 firmware" \
            --repo ${{ github.repository }}
      
